# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from speech_hub.auth.v1 import auth_service_pb2 as speech__hub_dot_auth_dot_v1_dot_auth__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in speech_hub/auth/v1/auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub:
    """AuthService defines the authentication service for validating and refreshing tokens.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.validate_token = channel.unary_unary(
                '/speech_hub.auth.v1.AuthService/validate_token',
                request_serializer=speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.refresh_token = channel.unary_unary(
                '/speech_hub.auth.v1.AuthService/refresh_token',
                request_serializer=speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """AuthService defines the authentication service for validating and refreshing tokens.
    """

    def validate_token(self, request, context):
        """validates the provided authentication token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def refresh_token(self, request, context):
        """generates a new authentication token for the user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'validate_token': grpc.unary_unary_rpc_method_handler(
                    servicer.validate_token,
                    request_deserializer=speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.ValidateTokenRequest.FromString,
                    response_serializer=speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'refresh_token': grpc.unary_unary_rpc_method_handler(
                    servicer.refresh_token,
                    request_deserializer=speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.RefreshTokenRequest.FromString,
                    response_serializer=speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.RefreshTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speech_hub.auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('speech_hub.auth.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """AuthService defines the authentication service for validating and refreshing tokens.
    """

    @staticmethod
    def validate_token(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech_hub.auth.v1.AuthService/validate_token',
            speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.ValidateTokenRequest.SerializeToString,
            speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def refresh_token(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech_hub.auth.v1.AuthService/refresh_token',
            speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.RefreshTokenRequest.SerializeToString,
            speech__hub_dot_auth_dot_v1_dot_auth__service__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
