services:
  loki:
    image: grafana/loki:2.9.2
    container_name: logger-loki-btl-python
    ports:
      - "127.0.0.1:7100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./infras/loki/config.yml:/etc/loki/local-config.yaml
      - loki_data:/loki
    environment:
      - LOKI_CONFIG_PATH=/etc/loki/local-config.yaml
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:10.1.5
    container_name: logger-grafana-btl-python
    ports:
      - "127.0.0.1:7000:3000"
    depends_on:
      - loki
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DATASOURCES_DEFAULT_TYPE=loki
      - GF_DATASOURCES_DEFAULT_URL=http://loki:3100
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infras/grafana/provisioning:/etc/grafana/provisioning
      - ./infras/grafana/dashboards:/etc/grafana/dashboards
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  loki_data:
  grafana_data: