# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from speech_hub.s2t.v1 import record_pb2 as speech__hub_dot_s2t_dot_v1_dot_record__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in speech_hub/s2t/v1/record_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecordingBackendServiceStub:
    """import "google/protobuf/timestamp.proto";

    Recording Backend Service - cung cấp cho AI Inference Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckQuota = channel.unary_unary(
                '/speech_hub.s2t.v1.RecordingBackendService/CheckQuota',
                request_serializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.CheckQuotaRequest.SerializeToString,
                response_deserializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.QuotaResponse.FromString,
                _registered_method=True)
        self.CreateRecording = channel.unary_unary(
                '/speech_hub.s2t.v1.RecordingBackendService/CreateRecording',
                request_serializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.CreateRecordingRequest.SerializeToString,
                response_deserializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.RecordingResponse.FromString,
                _registered_method=True)
        self.CompleteRecording = channel.unary_unary(
                '/speech_hub.s2t.v1.RecordingBackendService/CompleteRecording',
                request_serializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.CompleteRecordingRequest.SerializeToString,
                response_deserializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.RecordingResponse.FromString,
                _registered_method=True)
        self.UpdateRecordingStatus = channel.unary_unary(
                '/speech_hub.s2t.v1.RecordingBackendService/UpdateRecordingStatus',
                request_serializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.RecordingResponse.FromString,
                _registered_method=True)


class RecordingBackendServiceServicer:
    """import "google/protobuf/timestamp.proto";

    Recording Backend Service - cung cấp cho AI Inference Service
    """

    def CheckQuota(self, request, context):
        """1. Check quota trước khi bắt đầu recording
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRecording(self, request, context):
        """2. Tạo recording mới (sau khi check quota OK)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteRecording(self, request, context):
        """3. Hoàn thành recording + lưu segments
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRecordingStatus(self, request, context):
        """4. Update status nếu có lỗi
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecordingBackendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckQuota,
                    request_deserializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.CheckQuotaRequest.FromString,
                    response_serializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.QuotaResponse.SerializeToString,
            ),
            'CreateRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRecording,
                    request_deserializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.CreateRecordingRequest.FromString,
                    response_serializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.RecordingResponse.SerializeToString,
            ),
            'CompleteRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteRecording,
                    request_deserializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.CompleteRecordingRequest.FromString,
                    response_serializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.RecordingResponse.SerializeToString,
            ),
            'UpdateRecordingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRecordingStatus,
                    request_deserializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.UpdateStatusRequest.FromString,
                    response_serializer=speech__hub_dot_s2t_dot_v1_dot_record__pb2.RecordingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speech_hub.s2t.v1.RecordingBackendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('speech_hub.s2t.v1.RecordingBackendService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecordingBackendService:
    """import "google/protobuf/timestamp.proto";

    Recording Backend Service - cung cấp cho AI Inference Service
    """

    @staticmethod
    def CheckQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech_hub.s2t.v1.RecordingBackendService/CheckQuota',
            speech__hub_dot_s2t_dot_v1_dot_record__pb2.CheckQuotaRequest.SerializeToString,
            speech__hub_dot_s2t_dot_v1_dot_record__pb2.QuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech_hub.s2t.v1.RecordingBackendService/CreateRecording',
            speech__hub_dot_s2t_dot_v1_dot_record__pb2.CreateRecordingRequest.SerializeToString,
            speech__hub_dot_s2t_dot_v1_dot_record__pb2.RecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech_hub.s2t.v1.RecordingBackendService/CompleteRecording',
            speech__hub_dot_s2t_dot_v1_dot_record__pb2.CompleteRecordingRequest.SerializeToString,
            speech__hub_dot_s2t_dot_v1_dot_record__pb2.RecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRecordingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech_hub.s2t.v1.RecordingBackendService/UpdateRecordingStatus',
            speech__hub_dot_s2t_dot_v1_dot_record__pb2.UpdateStatusRequest.SerializeToString,
            speech__hub_dot_s2t_dot_v1_dot_record__pb2.RecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
