# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: speech_hub/auth/v1/auth_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'speech_hub/auth/v1/auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%speech_hub/auth/v1/auth_service.proto\x12\x12speech_hub.auth.v1\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"N\n\x15ValidateTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\x03\",\n\x13RefreshTokenRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\"9\n\x14RefreshTokenResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\x32\xd8\x01\n\x0b\x41uthService\x12\x65\n\x0evalidate_token\x12(.speech_hub.auth.v1.ValidateTokenRequest\x1a).speech_hub.auth.v1.ValidateTokenResponse\x12\x62\n\rrefresh_token\x12\'.speech_hub.auth.v1.RefreshTokenRequest\x1a(.speech_hub.auth.v1.RefreshTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_hub.auth.v1.auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATETOKENREQUEST']._serialized_start=61
  _globals['_VALIDATETOKENREQUEST']._serialized_end=98
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=100
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=178
  _globals['_REFRESHTOKENREQUEST']._serialized_start=180
  _globals['_REFRESHTOKENREQUEST']._serialized_end=224
  _globals['_REFRESHTOKENRESPONSE']._serialized_start=226
  _globals['_REFRESHTOKENRESPONSE']._serialized_end=283
  _globals['_AUTHSERVICE']._serialized_start=286
  _globals['_AUTHSERVICE']._serialized_end=502
# @@protoc_insertion_point(module_scope)
