"""add fully schema

Revision ID: 117a313fc715
Revises: cc36b1c7bdeb
Create Date: 2025-11-07 14:59:58.124166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117a313fc715'
down_revision: Union[str, Sequence[str], None] = 'cc36b1c7bdeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- BẮT ĐẦU SỬA LỖI ---
# 1. Định nghĩa biến Enum ở ngoài
userstatus_enum = sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus')
# --- KẾT THÚC SỬA LỖI ---


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. TẠO TYPE 'userstatus' TRƯỚC
    userstatus_enum.create(op.get_bind())

    # 2. Tạo tất cả các bảng (giữ nguyên)
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('plan_cost', sa.Integer(), nullable=False),
    sa.Column('plan_discount', sa.Integer(), nullable=False),
    sa.Column('monthly_minutes', sa.Integer(), nullable=False),
    sa.Column('monthly_usage_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('cycle_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cycle_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('used_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='unique_user_subscription')
    )
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transcript_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('recording_id', 'chunk_index', name='unique_recording_chunk')
    )

    # 3. THÊM CỘT 'status' VÀO 'users' (SỬ DỤNG TYPE ĐÃ TẠO)
    op.add_column('users', sa.Column(
        'status',
        userstatus_enum,  # Sử dụng biến đã định nghĩa
        nullable=False
    ))

    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Xóa constraint và cột 'status' (Đảo ngược)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'status')

    # 2. Xóa tất cả các bảng (Đảo ngược)
    op.drop_table('transcript_chunks')
    op.drop_table('segments')
    op.drop_table('user_subscriptions')
    op.drop_table('user_profiles')
    op.drop_table('recordings')
    op.drop_table('plans')

    # 3. XÓA TYPE 'userstatus' CUỐI CÙNG
    userstatus_enum.drop(op.get_bind())

    # ### end Alembic commands ###