"""add name for recording

Revision ID: 1a179c534d59
Revises: b75bcf727d7f
Create Date: 2025-11-11 22:00:36.522568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a179c534d59'
down_revision: Union[str, Sequence[str], None] = 'b75bcf727d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('name', sa.String(), server_default=sa.text("''"), nullable=False))
    op.create_unique_constraint(None, 'segment_words', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'segment_words', type_='unique')
    op.drop_column('recordings', 'name')
    # ### end Alembic commands ###
