"""fix

Revision ID: 85b209f2cad8
Revises: 117a313fc715
Create Date: 2025-11-08 11:12:30.307824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b209f2cad8'
down_revision: Union[str, Sequence[str], None] = '117a313fc715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# --- BẮT ĐẦU SỬA LỖI ---
# 1. Định nghĩa biến Enum ở ngoài
plan_type_enum = sa.Enum('FREE', 'BASIC', 'PREMIUM', 'ENTERPRISE', name='plan_type')
# --- KẾT THÚC SỬA LỖI ---


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 2. TẠO TYPE 'plan_type' TRƯỚC
    plan_type_enum.create(op.get_bind())

    # 3. THAY ĐỔI CỘT (ALTER COLUMN)
    op.alter_column('plans', 'plan_type',
               existing_type=sa.VARCHAR(),
               type_=plan_type_enum,
               existing_nullable=False,
               postgresql_using='plan_type::text::plan_type'
               )

    op.create_unique_constraint(None, 'plans', ['id'])
    op.create_unique_constraint(None, 'recordings', ['id'])
    op.create_unique_constraint(None, 'segments', ['id'])
    op.create_unique_constraint(None, 'transcript_chunks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Xóa các constraint (giữ nguyên)
    op.drop_constraint(None, 'transcript_chunks', type_='unique')
    op.drop_constraint(None, 'segments', type_='unique')
    op.drop_constraint(None, 'recordings', type_='unique')
    op.drop_constraint(None, 'plans', type_='unique')

    # 2. THAY ĐỔI CỘT VỀ LẠI VARCHAR
    op.alter_column('plans', 'plan_type',
               existing_type=plan_type_enum, # Sử dụng biến enum
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='plan_type::text::VARCHAR'
               )

    # 4. XÓA TYPE 'plan_type' CUỐI CÙNG
    plan_type_enum.drop(op.get_bind())

    # ### end Alembic commands ###