"""add record status

Revision ID: 8773c258e1ff
Revises: 85b209f2cad8
Create Date: 2025-11-08 13:19:35.216941

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8773c258e1ff'
down_revision: str | Sequence[str] | None = '85b209f2cad8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# --- BẮT ĐẦU SỬA LỖI ---
# 1. Định nghĩa biến Enum ở ngoài
record_status_enum = sa.Enum(
    'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED',
    name='record_status'
)
# --- KẾT THÚC SỬA LỖI ---


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 2. TẠO TYPE 'record_status' TRƯỚC
    record_status_enum.create(op.get_bind())

    # 3. THAY ĐỔI CỘT
    op.alter_column('recordings', 'status',
               existing_type=sa.VARCHAR(),
               type_=record_status_enum,
               existing_nullable=False,
               postgresql_using='status::text::record_status'
               )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. THAY ĐỔI CỘT VỀ LẠI VARCHAR
    op.alter_column('recordings', 'status',
               existing_type=record_status_enum,  # Sử dụng biến enum
               type_=sa.VARCHAR(),
               existing_nullable=False,
               # 2. Thêm 'using' để cast từ ENUM về VARCHAR
               postgresql_using='status::text::VARCHAR'
               )

    # 3. XÓA TYPE 'record_status' CUỐI CÙNG
    record_status_enum.drop(op.get_bind())

    # ### end Alembic commands ###
