"""add sth

Revision ID: ccf0e5a3c64d
Revises: 1a179c534d59
Create Date: 2025-11-12 02:00:51.307143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf0e5a3c64d'
down_revision: Union[str, Sequence[str], None] = '1a179c534d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user_subscriptions', sa.Column('plan_code_snapshot', sa.String(), nullable=False))
    op.add_column('user_subscriptions', sa.Column('plan_name_snapshot', sa.String(), nullable=False))
    op.add_column('user_subscriptions', sa.Column('plan_monthly_minutes_snapshot', sa.Integer(), nullable=False))
    op.add_column('user_subscriptions', sa.Column('plan_monthly_usage_limit_snapshot', sa.Integer(), nullable=False))
    op.alter_column('user_subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_subscriptions', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', 'plans', ['plan_id'], ['id'])
    op.alter_column('user_subscriptions', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('user_subscriptions', 'plan_monthly_usage_limit_snapshot')
    op.drop_column('user_subscriptions', 'plan_monthly_minutes_snapshot')
    op.drop_column('user_subscriptions', 'plan_name_snapshot')
    op.drop_column('user_subscriptions', 'plan_code_snapshot')
    op.drop_column('plans', 'is_active')
    op.drop_column('plans', 'is_default')
    # ### end Alembic commands ###
