"""init

Revision ID: f3c708206379
Revises:
Create Date: 2025-11-03 12:08:15.150317

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'f3c708206379'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
