# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: speech_hub/s2t/v1/record.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'speech_hub/s2t/v1/record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1espeech_hub/s2t/v1/record.proto\x12\x11speech_hub.s2t.v1\"$\n\x11\x43heckQuotaRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"9\n\rQuotaResponse\x12\x11\n\thas_quota\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"^\n\x16\x43reateRecordingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x11\n\tmeta_json\x18\x04 \x01(\t\"w\n\x18\x43ompleteRecordingRequest\x12\x14\n\x0crecording_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\x05\x12\x30\n\x08segments\x18\x03 \x03(\x0b\x32\x1e.speech_hub.s2t.v1.SegmentData\"J\n\x0bSegmentData\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x10\n\x08start_ms\x18\x02 \x01(\x05\x12\x0e\n\x06\x65nd_ms\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x04 \x01(\t\"i\n\x13UpdateStatusRequest\x12\x14\n\x0crecording_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x1a\n\rerror_message\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_error_message\"N\n\x11RecordingResponse\x12\x14\n\x0crecording_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x05\x32\xa2\x03\n\x17RecordingBackendService\x12T\n\nCheckQuota\x12$.speech_hub.s2t.v1.CheckQuotaRequest\x1a .speech_hub.s2t.v1.QuotaResponse\x12\x62\n\x0f\x43reateRecording\x12).speech_hub.s2t.v1.CreateRecordingRequest\x1a$.speech_hub.s2t.v1.RecordingResponse\x12\x66\n\x11\x43ompleteRecording\x12+.speech_hub.s2t.v1.CompleteRecordingRequest\x1a$.speech_hub.s2t.v1.RecordingResponse\x12\x65\n\x15UpdateRecordingStatus\x12&.speech_hub.s2t.v1.UpdateStatusRequest\x1a$.speech_hub.s2t.v1.RecordingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_hub.s2t.v1.record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKQUOTAREQUEST']._serialized_start=53
  _globals['_CHECKQUOTAREQUEST']._serialized_end=89
  _globals['_QUOTARESPONSE']._serialized_start=91
  _globals['_QUOTARESPONSE']._serialized_end=148
  _globals['_CREATERECORDINGREQUEST']._serialized_start=150
  _globals['_CREATERECORDINGREQUEST']._serialized_end=244
  _globals['_COMPLETERECORDINGREQUEST']._serialized_start=246
  _globals['_COMPLETERECORDINGREQUEST']._serialized_end=365
  _globals['_SEGMENTDATA']._serialized_start=367
  _globals['_SEGMENTDATA']._serialized_end=441
  _globals['_UPDATESTATUSREQUEST']._serialized_start=443
  _globals['_UPDATESTATUSREQUEST']._serialized_end=548
  _globals['_RECORDINGRESPONSE']._serialized_start=550
  _globals['_RECORDINGRESPONSE']._serialized_end=628
  _globals['_RECORDINGBACKENDSERVICE']._serialized_start=631
  _globals['_RECORDINGBACKENDSERVICE']._serialized_end=1049
# @@protoc_insertion_point(module_scope)
