# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from speech_hub.s2t.v1 import speech_to_text_pb2 as speech__hub_dot_s2t_dot_v1_dot_speech__to__text__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in speech_hub/s2t/v1/speech_to_text_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeechToTextStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeFromUri = channel.unary_unary(
                '/speech_hub.s2t.v1.SpeechToText/TranscribeFromUri',
                request_serializer=speech__hub_dot_s2t_dot_v1_dot_speech__to__text__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=speech__hub_dot_s2t_dot_v1_dot_speech__to__text__pb2.TranscribeResponse.FromString,
                _registered_method=True)


class SpeechToTextServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranscribeFromUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechToTextServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeFromUri': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeFromUri,
                    request_deserializer=speech__hub_dot_s2t_dot_v1_dot_speech__to__text__pb2.TranscribeRequest.FromString,
                    response_serializer=speech__hub_dot_s2t_dot_v1_dot_speech__to__text__pb2.TranscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'speech_hub.s2t.v1.SpeechToText', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('speech_hub.s2t.v1.SpeechToText', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechToText(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeFromUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/speech_hub.s2t.v1.SpeechToText/TranscribeFromUri',
            speech__hub_dot_s2t_dot_v1_dot_speech__to__text__pb2.TranscribeRequest.SerializeToString,
            speech__hub_dot_s2t_dot_v1_dot_speech__to__text__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
